version: "3"

services:
  graphdb:
    container_name: graphdb
    build:
      context: ./GraphDB
      dockerfile: Dockerfile
      args:
        version: 10.0.0
    restart: unless-stopped
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports:
      - 7201:7200
      - 7301:7300
    volumes:
      - ./GraphDB/graphdb-data:/opt/graphdb/home